---
title: "DATA 607 - Discussion 11"
author: "Ross Boehme"
date: "2023-04-19"
output: html_document
---

## Discussion Prompt

Your task is to analyze an existing recommender system that you find interesting.  You should:

1. Perform a Scenario Design analysis as described below. Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.
2. Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.
3. Include specific recommendations about how to improve the site's recommendation capabilities going forward. 
4. Create your report using an R Markdown file, and create a discussion thread with a link to the GitHub repo where your Markdown file notebook resides.  You are not expected to need to write code for this discussion assignment.

## LinkedIn Recommendation System 

### Scenario Design Analysis

Scenario design analysis consists of a three-question framework:

1. Who are your target users?
2. What are their key goals?
3. How can you help them accomplish these goals?

LinkedIn's target users are theoretically very viable worker in the world. They may specifically focus on their core demographic: white collar workers with reliable internet connections who have peers on LinkedIn. Because LinkedIn doesn't have any major competitors for business social networking, they don't need to target users of a different website.

The key goals of the LinkedIn recommendation engine are based on the key goals of the core demographic: Finding new jobs; Discovering new connections and keeping up with old connections; Reading workplace news such as layoffs, tips, acquisitions, etc.

These goals are accomplished as they are on Facebook and Twitter, by curating a personalized "news feed" via recommendation engine which contains this information in amounts proportional to activity. If LinkedIn tracks a user clicking on job openings, they can put more job openings posts in that user's feed. Same with adding more industry news to their feed, or more connection opportunities. 

### Reverse Engineering

The best resource I found for reverse engineering the algorithm was a [PowerPoint presentation](https://www.quora.com/How-does-LinkedIns-recommendation-system-work) made by software engineers Abhishek Gupta and Adil Aijaz at LinkedIn about their recommendation system. 

As Gupta and Aijaz tell it, they have an array of content they can enter into the feed. That content primarily consists of News, Job Postings, Connection Activity, and Posts from Followed Companies. They must balance the qualities of this information with a) Relevance to the user, b) Likelihood of engagement, and c) "Freshness". To do so, LinkedIn employs an algorithm for their recommendation engine which assesses which types of posts -- and from whom -- users tend to read and engage with the most. The main end goal for the algorithm is to keep the user on the site for as long as possible so LinkedIn can serve them as many ads as possible (the primary way LinkedIn makes their money). The algorithm adjusts itself through machine learning A/B tests to get the user to stay on as long as possible each time they visit.

### Possible Improvements

The LinkedIn algorithm is primarily *not* based on user choice but instead what actions the user takes on the website. The obvious exceptions are that users can mark themselves as "open to be contacted by recruiters" and can unfollow users/pages whose posts they don't want to see in their feed. I have the same wish for LinkedIn as I do for Facebook and Twitter: Deliberate user choice about what their feed looks like. For example, if a user only wants to see posts from their "Connections" or only business news, that should be possible. Instead LinkedIn, as Facebook and Twitter, let their algorithm self-reinforce user habits, despite their best wishes. I spend too much time scrolling LinkedIn, reading things I don't want to but which are compelling clickbait so they grab my attention. The algorithm then sends me more of this and I waste more time.

### Conclusion
The goal of LinkedIn's recommendation engine is the same as other attention economy companies: Maximize viewership duration in order to sell ads (and in the case of LinkedIn, potentially subscriptions to their Premium offering). This creates a race-to-the-bottom in terms of content, not necessarily giving users what they want but instead giving users what grabs their attention the most. 

I still believe in ad-based models because they democratize access to the Internet. For LinkedIn, going to a subscription-only model would create a bulwark against less wealthy people who want to find new jobs and professional connections. However, I wish that LinkedIn's recommendation engine could be informed by more visible user options about what they see and how often they see it.

My recommendation of more consumer choice in the recommendation engine may resonate with LinkedIn's target users of efficiency-oriented professionals who want to have personalized but productive feeds. While this might risk decreasing user time spent on site, I believe the new approach will make up for it monetarily via more meaningful interactions. If users come back to the site more often, even if they don't spend as long as they used to scrolling it, ad views will still be high, with more happily engaged professionals.